name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash
          git config --local user.email "bot@someemail.com"
          git config --local user.name "bot on GitHub Actions"

          git switch -c pr-branch
          echo "added by github action" > diff.log
          git add diff.log
          git commit -m "Commit from github action"
          git push -u origin pr-branch

          gh pr create --title "Add some diff" --body "Is it work?"
