name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash
          git config --local user.email "bot@someemail.com"
          git config --local user.name "bot on GitHub Actions"

          echo "added by github action" > test.log
          git add test.log
          git commit -m "Commit from github action"
          git push -u origin main
